language: julia
os:
    - osx
    - linux
julia:
    - stable
    - nightly
notifications:
    email: false
script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - julia -e 'Pkg.clone(pwd()); Pkg.build("DUPEsolang"); Pkg.test("DUPEsolang"; coverage=true)';
