language: julia
os:
    - osx
    - linux
julia:
    - 1
    - nightly
notifications:
    email: false
script:
    using Pkg
    Pkg.build(; verbose = true) #Pkg.build() # Pkg.build(; verbose = true) for Julia 1.1 and up
    Pkg.test(coverage=true)