# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
  - 0.4+
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.init(); Pkg.clone("https://github.com/m-lohmann/DUPEsolang.jl")'
  - julia -e 'Pkg.test("DUPEsolang",coverage=true)'
#after_success:
#  - julia -e 'Pkg.clone("https://github.com/MichaelHatherly/Documenter.jl")'
#  - julia -e 'cd(Pkg.dir("DUPEsolang")); include(joinpath("docs", "make.jl"))'
#  - julia -e 'cd(Pkg.dir("DUPEsolang")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
#  - julia -e 'cd(Pkg.dir("DUPEsolang")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
