# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
  - 0.4+
notifications:
  email: false
# uncomment the following lines to override the default test script
script:
 - julia -e 'Pkg.clone(pwd())'
 - julia -e 'Pkg.build("$name")'
 - if [ -f test/runtests.jl ]; then
 -   julia --check-bounds=yes -e 'Pkg.test("$name", coverage=true)'
 - fi
